version: "3.3"
   
services:

  db:
    image: postgres:14
    container_name: convoyor_db
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
  api:
    build: ./api
    command: bash -c "python manage.py runserver 0.0.0.0:${API_PORT}"
    container_name: convoyor_api
    restart: always
    volumes:
      - ./api/code:/code
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - API_ALLOWED_HOSTS=${API_ALLOWED_HOSTS}
    depends_on:
      - db
  
  grafana:
    container_name: convoyor_grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "1001"
    restart: unless-stopped
    volumes:
      # - ./volumes/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      # - ./volumes/grafana/grafana-data:/var/lib/grafana
      - grafana-datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
      
volumes:
  postgres:
    name: convoyor_postgres_data
  grafana-datasources:
    name: convoyor_grafana-datasources
  grafana-data:
    name: convoyor_grafana-data