# Generated by Django 3.2.17 on 2023-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoyeur', '0004_alter_package_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.CharField(choices=[('Straight', 'Straight'), ('Right', 'Right'), ('Left', 'Left')], max_length=10),
        ),
    ]
