# Generated by Django 3.2.17 on 2023-02-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoyeur', '0012_alter_package_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='package',
            name='scanned',
        ),
        migrations.RemoveField(
            model_name='package',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.CharField(choices=[('Left', 'Left'), ('Straight', 'Straight'), ('Right', 'Right')], max_length=10),
        ),
    ]
