# Generated by Django 3.2.17 on 2023-02-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoyeur', '0014_auto_20230205_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Straight', 'Straight')], max_length=10),
        ),
    ]
